CREATE DATABASE ACCENTUREMARKET;
CREATE TABLE CATEGORIAS (
  [IDCATEGORIA] int IDENTITY(1, 1) NOT NULL,
  [DESCRIPCION] varchar(45) NOT NULL,
  [ESTADO] bit NOT NULL,
  PRIMARY KEY ([IDCATEGORIA])
);
CREATE TABLE PRODUCTOS (
  [IDPRODCUTO] int IDENTITY(1, 1) NOT NULL,
  [NOMBRE] varchar(45) NULL,
  [IDCATEGORIA] int NOT NULL,
  [CODIGOBARRAS] varchar(150) NULL,
  [PRECIOVENTA] decimal(16, 2) NULL,
  [CANTIDADSTOCK] int NOT NULL,
  [ESTADO] bit NULL,
  PRIMARY KEY ([IDPRODCUTO]),
  CONSTRAINT [FK_PRODUCTOS_CATEGORIAS]
    FOREIGN KEY ([IDCATEGORIA])
    REFERENCES CATEGORIAS ([IDCATEGORIA]) ON DELETE NO ACTION ON UPDATE NO ACTION
);
